version: "3.3"
services:
  db:
    container_name: maki-db
    image: postgres:11.5
    ports: 
      - "5454:5432"
    restart: always
    volumes:
      - maki-pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: maki
      POSTGRES_DB: makiblog
      POSTGRES_PASSWORD: makidebug
      PGPORT: 5432
      PGOPTS: "-i"

volumes:
  maki-pg-data:
